# Generated by Django 5.2.17 on 2026-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✳', max_length=10, verbose_name='Значок (эмодзи/символ)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок карточки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Карточка заботы',
                'verbose_name_plural': 'Карточки заботы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото в галерее',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(max_length=200, verbose_name='Надпись над заголовком')),
                ('hero_heading', models.TextField(help_text='Перенос строки — новая строка в заголовке.', verbose_name='Заголовок (обычная часть)')),
                ('hero_heading_accent', models.CharField(max_length=100, verbose_name='Заголовок (выделенная часть)')),
                ('hero_description', models.TextField(verbose_name='Описание под заголовком')),
                ('hero_button_primary_text', models.CharField(max_length=100, verbose_name='Текст основной кнопки')),
                ('hero_button_secondary_text', models.CharField(max_length=100, verbose_name='Текст второй ссылки')),
                ('hero_proof_text', models.CharField(max_length=200, verbose_name='Текст про количество собак')),
                ('hero_photo', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Главное фото')),
                ('hero_photo_caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись на фото')),
                ('hero_sticker_text', models.CharField(blank=True, max_length=100, verbose_name='Текст на наклейке')),
                ('about_eyebrow', models.CharField(max_length=200, verbose_name='Надпись над заголовком')),
                ('about_heading', models.TextField(verbose_name='Заголовок (обычная часть)')),
                ('about_heading_accent', models.CharField(max_length=100, verbose_name='Заголовок (выделенная часть)')),
                ('about_paragraph_1', models.TextField(verbose_name='Первый абзац')),
                ('about_paragraph_2', models.TextField(verbose_name='Второй абзац')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото')),
                ('about_image_stamp', models.CharField(blank=True, max_length=100, verbose_name='Текст на фото')),
                ('about_link_text', models.CharField(max_length=200, verbose_name='Текст ссылки вниз')),
                ('care_eyebrow', models.CharField(max_length=200, verbose_name='Надпись над заголовком')),
                ('care_heading', models.TextField(verbose_name='Заголовок (обычная часть)')),
                ('care_heading_accent', models.CharField(max_length=100, verbose_name='Заголовок (выделенная часть)')),
                ('care_description', models.TextField(verbose_name='Описание')),
                ('gallery_eyebrow', models.CharField(max_length=200, verbose_name='Надпись над заголовком')),
                ('gallery_heading', models.TextField(verbose_name='Заголовок (обычная часть)')),
                ('gallery_heading_accent', models.CharField(max_length=100, verbose_name='Заголовок (выделенная часть)')),
                ('gallery_note', models.TextField(verbose_name='Текст-примечание')),
                ('contact_eyebrow', models.CharField(max_length=200, verbose_name='Надпись над заголовком')),
                ('contact_heading', models.TextField(verbose_name='Заголовок (обычная часть)')),
                ('contact_heading_accent', models.CharField(max_length=100, verbose_name='Заголовок (выделенная часть)')),
                ('contact_description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram_url', models.URLField(verbose_name='Ссылка на Telegram')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('hours', models.TextField(verbose_name='Часы приёма')),
                ('map_note', models.CharField(max_length=300, verbose_name='Короткая фраза под адресом')),
                ('footer_tagline', models.CharField(max_length=200, verbose_name='Фраза в подвале')),
                ('footer_copyright', models.CharField(max_length=200, verbose_name='Копирайт в подвале')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Цифра',
                'verbose_name_plural': 'Цифры (статистика)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Короткая фраза',
                'verbose_name_plural': 'Бегущая строка (короткие фразы)',
                'ordering': ['order'],
            },
        ),
    ]
