# Generated by Django 5.2.17 on 2026-10-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='KinologyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга (тег)',
                'verbose_name_plural': 'Кинология — услуги (теги)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Короткая фраза')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('yandex_maps_url', models.URLField(blank=True, verbose_name='Ссылка на Яндекс.Карты')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Пункт списка',
                'verbose_name_plural': 'Что взять с собой',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='kinology_description',
            field=models.TextField(default='', verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='kinology_eyebrow',
            field=models.CharField(default='', max_length=200, verbose_name='Надпись над заголовком'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='kinology_heading',
            field=models.TextField(default='', verbose_name='Заголовок (обычная часть)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='kinology_heading_accent',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок (выделенная часть)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='kinology_instagram_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='kinology_telegram_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_choice_apartment_text',
            field=models.TextField(default='', verbose_name='Описание варианта 1 (квартира)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_choice_apartment_title',
            field=models.CharField(default='Квартира', max_length=100, verbose_name='Название варианта 1'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_choice_heading',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок блока «Как выбрать локацию»'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_choice_house_text',
            field=models.TextField(default='', verbose_name='Описание варианта 2 (дом)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_choice_house_title',
            field=models.CharField(default='Дом', max_length=100, verbose_name='Название варианта 2'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_eyebrow',
            field=models.CharField(default='', max_length=200, verbose_name='Надпись над заголовком'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_heading',
            field=models.TextField(default='', verbose_name='Заголовок (обычная часть)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_heading_accent',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок (выделенная часть)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='locations_intro',
            field=models.TextField(default='', verbose_name='Вводный текст про локации'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='packing_eyebrow',
            field=models.CharField(default='', max_length=200, verbose_name='Надпись над заголовком'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='packing_heading',
            field=models.TextField(default='', verbose_name='Заголовок (обычная часть)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='packing_heading_accent',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок (выделенная часть)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='packing_intro',
            field=models.TextField(default='', verbose_name='Вводный текст'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='quiet_hour_eyebrow',
            field=models.CharField(default='', max_length=200, verbose_name='Надпись над заголовком'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='quiet_hour_heading',
            field=models.TextField(default='', verbose_name='Заголовок (обычная часть)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='quiet_hour_heading_accent',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок (выделенная часть)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='quiet_hour_photo',
            field=models.ImageField(blank=True, null=True, upload_to='quiet-hour/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='quiet_hour_text',
            field=models.TextField(default='', verbose_name='Текст про тихий час'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.CreateModel(
            name='LocationHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='main.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Особенность локации',
                'verbose_name_plural': 'Особенности локации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='locations/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Фото локации',
                'verbose_name_plural': 'Фото локации',
                'ordering': ['order'],
            },
        ),
    ]
